model_path_or_id: small.en
device: cpu
observed_path: C:/Users/kryst/Documents/Sound recordings
transcription_destination_path: C:/Users/kryst/Documents/transcriptions
processed_files_path: ''
upload_lag: 10
